import { C } from './state.js';
import { cur, fd, now, gCT, gLoc, gCC } from './utils.js';
import { getFiltrosRel } from './relatorios.js';
import { slog, toast } from './utils.js';

export function gerarExcelSimples(nome, rows){
  const enc = new TextEncoder();
  function xe(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  function le16(n){return[n&0xFF,(n>>8)&0xFF];}
  function le32(n){return[n&0xFF,(n>>8)&0xFF,(n>>16)&0xFF,(n>>24)&0xFF];}
  function cat(...a){const r=new Uint8Array(a.reduce((s,x)=>s+x.length,0));let o=0;for(const x of a){r.set(x,o);o+=x.length;}return r;}
  function crc32(u){const t=new Int32Array(256);for(let i=0;i<256;i++){let c=i;for(let j=0;j<8;j++)c=c&1?(0xEDB88320^(c>>>1)):c>>>1;t[i]=c;}let c=-1;for(const b of u)c=t[(c^b)&0xFF]^(c>>>8);return(c^-1)>>>0;}
  function ze(name,data){const nb=enc.encode(name),crc=crc32(data);return{name,nb,data,crc,lh:new Uint8Array([0x50,0x4B,0x03,0x04,20,0,0,0,0,0,0,0,0,0,...le32(crc),...le32(data.length),...le32(data.length),...le16(nb.length),0,0]),offset:0};}
  function bzip(es){const pts=[];let off=0;for(const e of es){e.offset=off;pts.push(e.lh,enc.encode(e.name),e.data);off+=e.lh.length+enc.encode(e.name).length+e.data.length;}const cd=[];let cdl=0;for(const e of es){const nb=enc.encode(e.name);const r=new Uint8Array([0x50,0x4B,0x01,0x02,20,0,20,0,0,0,0,0,0,0,0,0,...le32(e.crc),...le32(e.data.length),...le32(e.data.length),...le16(nb.length),0,0,0,0,0,0,0,0,0,0,0,0,...le32(e.offset)]);cd.push(r,nb);cdl+=r.length+nb.length;}return cat(...pts,...cd,new Uint8Array([0x50,0x4B,0x05,0x06,0,0,0,0,...le16(es.length),...le16(es.length),...le32(cdl),...le32(off),0,0]));}
  // Shared strings
  const ss=[];const si=v=>{const s=String(v==null?'':v);if(!ss.includes(s))ss.push(s);return ss.indexOf(s);};
  rows.forEach(row=>row.forEach(c=>{if(typeof c!=='number')si(String(c==null?'':c));}));
  // Worksheet — header na linha 1 negrito azul, dados a partir linha 2
  let wx=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">`;
  wx+=`<sheetViews><sheetView workbookViewId="0"><selection activeCell="A2" sqref="A2"/></sheetView></sheetViews>`;
  wx+=`<sheetData>`;
  rows.forEach((row,ri)=>{
    const isHeader = ri===0;
    wx+=`<row r="${ri+1}" ht="${isHeader?18:15}" customHeight="1">`;
    row.forEach((v,ci)=>{
      const col=String.fromCharCode(65+ci);
      const ref=`${col}${ri+1}`;
      const sty=isHeader?'1':'2';
      if(typeof v==='number') wx+=`<c r="${ref}" s="${sty}" t="n"><v>${v}</v></c>`;
      else wx+=`<c r="${ref}" s="${sty}" t="s"><v>${si(String(v==null?'':v))}</v></c>`;
    });
    wx+=`</row>`;
  });
  wx+=`</sheetData><sheetProtection/></worksheet>`;
  const ssXml=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="${ss.length}" uniqueCount="${ss.length}">${ss.map(s=>`<si><t xml:space="preserve">${xe(s)}</t></si>`).join('')}</sst>`;
  const stXml=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="10"/><name val="Calibri"/></font><font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF1d6fdf"/></fgColor></patternFill></fill></fills><borders count="2"><border><left/><right/><top/><bottom/></border><border><left style="thin"><color rgb="FFCBD5E1"/></left><right style="thin"><color rgb="FFCBD5E1"/></right><top style="thin"><color rgb="FFCBD5E1"/></top><bottom style="thin"><color rgb="FFCBD5E1"/></bottom></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="1" applyFont="1" applyFill="1" applyBorder="1"><alignment horizontal="center" vertical="center" wrapText="0"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="1" applyBorder="1"><alignment vertical="center"/></xf></cellXfs></styleSheet>`;
  const wbXml=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Importacao" sheetId="1" r:id="rId3"/></sheets></workbook>`;
  const wbR=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>`;
  const ct2=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/xl/sharedStrings.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>`;
  const rr=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`;
  const entries=[ze('[Content_Types].xml',enc.encode(ct2)),ze('_rels/.rels',enc.encode(rr)),ze('xl/workbook.xml',enc.encode(wbXml)),ze('xl/_rels/workbook.xml.rels',enc.encode(wbR)),ze('xl/styles.xml',enc.encode(stXml)),ze('xl/sharedStrings.xml',enc.encode(ssXml)),ze('xl/worksheets/sheet1.xml',enc.encode(wx))];
  const blob=new Blob([bzip(entries)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
  const url=URL.createObjectURL(blob);
  const a=document.createElement('a');a.href=url;a.download=nome+'.xlsx';
  document.body.appendChild(a);a.click();
  setTimeout(()=>{URL.revokeObjectURL(url);a.remove();},500);
}

export function exportarExcel(tipo){
  toast('⏳ Gerando Excel...','i');
  setTimeout(()=>{
    try{
      const dt=new Date().toLocaleDateString('pt-BR').replace(/\//g,'-');
      const enc=new TextEncoder();
      function xe(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
      function crc32(u){const t=new Int32Array(256);for(let i=0;i<256;i++){let c=i;for(let j=0;j<8;j++)c=c&1?(0xEDB88320^(c>>>1)):c>>>1;t[i]=c;}let c=-1;for(const b of u)c=t[(c^b)&0xFF]^(c>>>8);return(c^-1)>>>0;}
      function le16(n){return[n&0xFF,(n>>8)&0xFF];}
      function le32(n){return[n&0xFF,(n>>8)&0xFF,(n>>16)&0xFF,(n>>24)&0xFF];}
      function cat(...a){const r=new Uint8Array(a.reduce((s,x)=>s+x.length,0));let o=0;for(const x of a){r.set(x,o);o+=x.length;}return r;}
      function ze(name,data){const nb=enc.encode(name),crc=crc32(data);return{name,nb,data,crc,lh:new Uint8Array([0x50,0x4B,0x03,0x04,20,0,0,0,0,0,0,0,0,0,...le32(crc),...le32(data.length),...le32(data.length),...le16(nb.length),0,0]),offset:0};}
      function bzip(es){const pts=[];let off=0;for(const e of es){e.offset=off;pts.push(e.lh,enc.encode(e.name),e.data);off+=e.lh.length+enc.encode(e.name).length+e.data.length;}const cd=[];let cdl=0;for(const e of es){const nb=enc.encode(e.name);const r=new Uint8Array([0x50,0x4B,0x01,0x02,20,0,20,0,0,0,0,0,0,0,0,0,...le32(e.crc),...le32(e.data.length),...le32(e.data.length),...le16(nb.length),0,0,0,0,0,0,0,0,0,0,0,0,...le32(e.offset)]);cd.push(r,nb);cdl+=r.length+nb.length;}return cat(...pts,...cd,new Uint8Array([0x50,0x4B,0x05,0x06,0,0,0,0,...le16(es.length),...le16(es.length),...le32(cdl),...le32(off),0,0]));}
      function buildXLSX(sheets){
        const ss=[];const si=v=>{const s=String(v==null?'':v);if(!ss.includes(s))ss.push(s);return ss.indexOf(s);};
        for(const sh of sheets){si(sh.t);sh.h.forEach(h=>si(h));sh.r.forEach(r=>r.forEach(c=>{if(typeof c!=='number')si(String(c==null?'':c));}));}
        const shXmls=sheets.map(sh=>{
          let x=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">`;
          if(sh.w)x+=`<cols>${sh.w.map((w,i)=>`<col min="${i+1}" max="${i+1}" width="${w}" customWidth="1"/>`).join('')}</cols>`;
          x+=`<sheetData><row r="1" ht="22" customHeight="1"><c r="A1" s="1" t="s"><v>${si(sh.t)}</v></c></row><row r="2" ht="16" customHeight="1">`;
          sh.h.forEach((h,i)=>{x+=`<c r="${String.fromCharCode(65+i)}2" s="2" t="s"><v>${si(h)}</v></c>`;});x+=`</row>`;
          sh.r.forEach((row,ri)=>{const s=ri%2===0?3:4;x+=`<row r="${ri+3}">`;row.forEach((v,ci)=>{if(typeof v==='number')x+=`<c r="${String.fromCharCode(65+ci)}${ri+3}" s="${s}" t="n"><v>${v}</v></c>`;else x+=`<c r="${String.fromCharCode(65+ci)}${ri+3}" s="${s}" t="s"><v>${si(String(v==null?'':v))}</v></c>`;});x+=`</row>`;});
          x+=`</sheetData></worksheet>`;return x;
        });
        const ssXml=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="${ss.length}" uniqueCount="${ss.length}">${ss.map(s=>`<si><t xml:space="preserve">${xe(s)}</t></si>`).join('')}</sst>`;
        const wbXml=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map((s,i)=>`<sheet name="${xe(s.n)}" sheetId="${i+1}" r:id="rId${i+3}"/>`).join('')}</sheets></workbook>`;
        const wbR=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml"/>${sheets.map((_,i)=>`<Relationship Id="rId${i+3}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}</Relationships>`;
        const stXml=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="3"><font><sz val="10"/><name val="Calibri"/></font><font><b/><sz val="12"/><name val="Calibri"/><color rgb="FFFFFFFF"/></font><font><b/><sz val="10"/><name val="Calibri"/></font></fonts><fills count="5"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF1e3a8a"/></fgColor></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFdbeafe"/></fgColor></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFFFFFF"/></fgColor></patternFill></fills><borders count="2"><border><left/><right/><top/><bottom/></border><border><left style="thin"><color rgb="FFCBD5E1"/></left><right style="thin"><color rgb="FFCBD5E1"/></right><top style="thin"><color rgb="FFCBD5E1"/></top><bottom style="thin"><color rgb="FFCBD5E1"/></bottom></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="5"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="1" applyFill="1" applyFont="1" applyBorder="1"><alignment horizontal="center" vertical="center"/></xf><xf numFmtId="0" fontId="2" fillId="2" borderId="1" applyFill="1" applyFont="1" applyBorder="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="3" borderId="1" applyFill="1" applyBorder="1"><alignment vertical="center"/></xf><xf numFmtId="0" fontId="0" fillId="4" borderId="1" applyFill="1" applyBorder="1"><alignment vertical="center"/></xf></cellXfs></styleSheet>`;
        const ct2=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/xl/sharedStrings.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`;
        const rr=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`;
        const entries=[ze('[Content_Types].xml',enc.encode(ct2)),ze('_rels/.rels',enc.encode(rr)),ze('xl/workbook.xml',enc.encode(wbXml)),ze('xl/_rels/workbook.xml.rels',enc.encode(wbR)),ze('xl/styles.xml',enc.encode(stXml)),ze('xl/sharedStrings.xml',enc.encode(ssXml)),...shXmls.map((x,i)=>ze(`xl/worksheets/sheet${i+1}.xml`,enc.encode(x)))];
        return new Blob([bzip(entries)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
      }
      const SH=[],LBL='SULBAIANA EMPREENDIMENTOS LTDA. — ';
      if(['completo','contratos'].includes(tipo)){const rows=C.ct.map(ct=>{const ids=C.v.filter(v=>v.contrato_id===ct.id).map(v=>v.id);const cm=C.m.filter(m=>ids.includes(m.veiculo_id)).reduce((s,m)=>s+Number(m.valor),0);const ca=C.a.filter(a=>ids.includes(a.veiculo_id)).reduce((s,a)=>s+Number(a.valor_total),0);return[ct.nome_contrato,ct.numero_contrato||'',fd(ct.data_inicio),fd(ct.data_fim),ids.length,parseFloat(cm.toFixed(2)),parseFloat(ca.toFixed(2)),parseFloat((cm+ca).toFixed(2)),ct.status];});SH.push({n:'CONTRATOS',t:LBL+'Por Contrato | '+dt,h:['CONTRATO','NÚMERO','INÍCIO','FIM','VEÍCULOS','MANUT (R$)','COMB (R$)','TOTAL (R$)','STATUS'],r:rows,w:[28,14,12,12,10,16,16,16,10]});}
      if(['completo','localidades'].includes(tipo)){const rows=C.loc.map(l=>{const ids=C.v.filter(v=>v.localidade_id===l.id).map(v=>v.id);const cm=C.m.filter(m=>ids.includes(m.veiculo_id)).reduce((s,m)=>s+Number(m.valor),0);const ca=C.a.filter(a=>ids.includes(a.veiculo_id)).reduce((s,a)=>s+Number(a.valor_total),0);return[l.nome_localidade,l.cidade||'',l.estado||'',ids.length,parseFloat(cm.toFixed(2)),parseFloat(ca.toFixed(2)),parseFloat((cm+ca).toFixed(2)),l.status];});SH.push({n:'LOCALIDADES',t:LBL+'Por Localidade | '+dt,h:['LOCALIDADE','CIDADE','UF','VEÍCULOS','MANUT (R$)','COMB (R$)','TOTAL (R$)','STATUS'],r:rows,w:[18,16,6,10,16,16,16,10]});}
      if(['completo','custo_cc'].includes(tipo)){const rows=C.cc.map(c=>{const ids=C.v.filter(v=>v.centro_custo_id===c.id).map(v=>v.id);const cm=C.m.filter(m=>ids.includes(m.veiculo_id)).reduce((s,m)=>s+Number(m.valor),0);const ca=C.a.filter(a=>ids.includes(a.veiculo_id)).reduce((s,a)=>s+Number(a.valor_total),0);return[c.nome,gCT(c.contrato_id).nome_contrato,gLoc(c.localidade_id).nome_localidade,ids.length,parseFloat(cm.toFixed(2)),parseFloat(ca.toFixed(2)),parseFloat((cm+ca).toFixed(2)),c.status];});SH.push({n:'CENTROS CC',t:LBL+'Por Centro de Custo | '+dt,h:['CENTRO','CONTRATO','LOCALIDADE','VEÍCULOS','MANUT (R$)','COMB (R$)','TOTAL (R$)','STATUS'],r:rows,w:[18,24,16,10,16,16,16,10]});}
      if(['completo','analitico'].includes(tipo)){const rows=[...C.v].map(v=>{const cm=C.m.filter(m=>m.veiculo_id===v.id).reduce((s,m)=>s+Number(m.valor),0);const ca=C.a.filter(a=>a.veiculo_id===v.id).reduce((s,a)=>s+Number(a.valor_total),0);const dep=parseFloat(Number(v.valor_depreciacao||0).toFixed(2));const loc=parseFloat(Number(v.valor_locacao||0).toFixed(2));return[v.placa,v.modelo,v.ano||'',v.tipo||'',gCT(v.contrato_id).nome_contrato,gLoc(v.localidade_id).nome_localidade,gCC(v.centro_custo_id).nome,v.responsavel||'',v.status,v.km_atual||0,parseFloat(cm.toFixed(2)),parseFloat(ca.toFixed(2)),dep,loc,parseFloat((cm+ca+dep+loc).toFixed(2))];}).sort((a,b)=>b[14]-a[14]);SH.push({n:'VEÍCULOS',t:LBL+'Analítico Veículos | '+dt,h:['PLACA','MODELO','ANO','TIPO','CONTRATO','LOCALIDADE','CENTRO CC','RESPONSÁVEL','STATUS','KM','MANUT (R$)','COMB (R$)','DEPRECIAÇÃO (R$)','LOCAÇÃO (R$)','TOTAL (R$)'],r:rows,w:[12,18,6,8,24,16,18,28,10,12,14,14,14,14,14]});}
      if(['completo','combustivel'].includes(tipo)){const rows=C.a.map(a=>{const v=window.gV(a.veiculo_id);const prev=C.a.filter(x=>x.veiculo_id===a.veiculo_id&&x.km_atual<a.km_atual).sort((x,y)=>y.km_atual-x.km_atual)[0];const kmr=prev?a.km_atual-prev.km_atual:0;const kml=kmr>0&&a.litros>0?parseFloat((kmr/a.litros).toFixed(2)):0;return[v.placa,v.modelo,gCT(v.contrato_id).nome_contrato,gLoc(v.localidade_id).nome_localidade,fd(a.data),a.km_atual||0,parseFloat(Number(a.litros).toFixed(3)),parseFloat(Number(a.valor_total).toFixed(2)),a.tipo_combustivel||'',a.posto||'',kml,kmr];});SH.push({n:'COMBUSTÍVEL',t:LBL+'Combustível | '+dt,h:['PLACA','MODELO','CONTRATO','LOCALIDADE','DATA','KM','LITROS','VALOR (R$)','TIPO','POSTO','KM/L','KM RODADO'],r:rows,w:[12,18,22,14,12,10,10,14,10,22,8,12]});}
      if(['completo','manutencao'].includes(tipo)){const rows=C.m.map(m=>{const v=window.gV(m.veiculo_id);return[v.placa,v.modelo,gCT(v.contrato_id).nome_contrato,gLoc(v.localidade_id).nome_localidade,m.tipo_servico,m.descricao||'',fd(m.data),m.km||0,parseFloat(Number(m.valor).toFixed(2)),gCC(m.centro_custo_id).nome,m.nf?'Sim':'Não'];});SH.push({n:'MANUTENÇÃO',t:LBL+'Manutenção | '+dt,h:['PLACA','MODELO','CONTRATO','LOCALIDADE','TIPO','DESCRIÇÃO','DATA','KM','VALOR (R$)','CENTRO CC','NF'],r:rows,w:[12,18,22,14,16,36,12,10,14,16,8]});}
      if(['completo','mensal'].includes(tipo)){const meses=[...new Set([...C.a.map(a=>a.data?.slice(0,7)),...C.m.map(m=>m.data?.slice(0,7))].filter(Boolean))].sort().reverse();const rows=meses.map(m=>{const ca=C.a.filter(a=>a.data?.startsWith(m)).reduce((s,a)=>s+Number(a.valor_total),0);const cm=C.m.filter(x=>x.data?.startsWith(m)).reduce((s,x)=>s+Number(x.valor),0);const[y,mo]=m.split('-');return[`${mo}/${y}`,C.a.filter(a=>a.data?.startsWith(m)).length,C.m.filter(x=>x.data?.startsWith(m)).length,parseFloat(ca.toFixed(2)),parseFloat(cm.toFixed(2)),parseFloat((ca+cm).toFixed(2))];});SH.push({n:'MENSAL',t:LBL+'Consolidado Mensal | '+dt,h:['MÊS','ABASTECIMENTOS','MANUTENÇÕES','COMB (R$)','MANUT (R$)','TOTAL (R$)'],r:rows,w:[10,16,14,16,16,16]});}
      if(['completo','status'].includes(tipo)){const f2=getFiltrosRel();let vs=C.v;if(f2.ct)vs=vs.filter(v=>v.contrato_id==f2.ct);if(f2.statusV)vs=vs.filter(v=>v.status===f2.statusV);const rows=vs.map(v=>[v.placa,v.modelo,v.tipo||'',gCT(v.contrato_id).nome_contrato,gLoc(v.localidade_id).nome_localidade,v.status,v.km_atual||0,v.responsavel||'',(v.tipo_frota||'propria')==='locada'?'Locado':'Próprio']);SH.push({n:'STATUS',t:LBL+'Status de Veículos | '+dt,h:['PLACA','MODELO','TIPO','CONTRATO','LOCALIDADE','STATUS','KM','RESPONSÁVEL','FROTA'],r:rows,w:[12,18,8,24,16,14,10,24,10]});}
      if(['completo','frota'].includes(tipo)){const f2=getFiltrosRel();let veicsFrota=C.v;if(f2.ct)veicsFrota=veicsFrota.filter(v=>v.contrato_id==f2.ct);if(f2.frota)veicsFrota=veicsFrota.filter(v=>(v.tipo_frota||'propria')===f2.frota);const rows=veicsFrota.map(v=>[v.placa,v.modelo,v.renavan||'—',v.ano||'',v.tipo||'',gCT(v.contrato_id).nome_contrato,gLoc(v.localidade_id).nome_localidade,v.responsavel||'',v.status,(v.tipo_frota||'propria')==='locada'?'Veículo Locado':'Frota Própria',parseFloat(Number(v.valor_depreciacao||0).toFixed(2)),parseFloat(Number(v.valor_locacao||0).toFixed(2)),v.locador_nome||'—',v.locador_email||'—',v.locador_fone||'—']);SH.push({n:'FROTA',t:LBL+'Relatório de Frota | '+dt,h:['PLACA','MODELO','RENAVAN','ANO','TIPO','CONTRATO','LOCALIDADE','RESPONSÁVEL','STATUS','TIPO FROTA','DEPRECIAÇÃO (R$)','LOCAÇÃO (R$)','LOCADOR','E-MAIL','TELEFONE'],r:rows,w:[12,18,14,6,8,24,16,24,10,14,14,14,24,24,16]});}
      if(!SH.length){toast('Nenhum dado para exportar','i');return;}
      const blob=buildXLSX(SH);
      const url=URL.createObjectURL(blob);
      const a=document.createElement('a');
      const nms={completo:'Frota_Completo',contratos:'Por_Contrato',localidades:'Por_Localidade',custo_cc:'Por_Centro',analitico:'Analitico',combustivel:'Combustivel',manutencao:'Manutencao',mensal:'Mensal',frota:'Relatorio_Frota',movimentacoes:'Movimentacoes',status:'Status_Veiculos'};
      a.href=url;a.download=`Sulbaiana_${nms[tipo]||tipo}_${dt}.xlsx`;
      document.body.appendChild(a);a.click();
      setTimeout(()=>{URL.revokeObjectURL(url);a.remove();},500);
      slog(`Excel exportado: ${tipo}`);toast('✅ Excel gerado!');
    }catch(e){console.error(e);toast('❌ Erro: '+e.message,'e');}
  },80);
}

// Make globally accessible
window.gerarExcelSimples = gerarExcelSimples;
window.exportarExcel = exportarExcel;
